#pragma once
// Generated by Tools/arena_dimensions.py --write-header. Units: centimetres.
// GoalPlaneX is distinct from the end-net HalfLength.
namespace BBArena
{
inline constexpr double VolumeScale = 1.45;
inline constexpr double LinearScale = 1.1318511959629507;
inline constexpr double GoalPlaneX = 7244.7531351196549;
inline constexpr double HalfLength = 7754.0861733029824;
inline constexpr double HalfWidth = 3622.3765675598274;
inline constexpr double EaveHeight = 4760.8377745072012;
inline constexpr double ApexHeight = 7141.2566617608027;
inline constexpr double LargeHoopHeight = 2103.1199999999999;
inline constexpr double SmallHoopHeight = 3048;
inline constexpr double HoopSpacing = 1066.8;
inline constexpr double LargeHoopRadius = 335.27999999999997;
inline constexpr double SmallHoopRadius = 198.12;
inline constexpr double FreeShotDistance = 1341.1199999999999;
inline constexpr double RestartDistance = 670.55999999999995;
}
