#pragma once
// generated by Tools/arena_dimensions.py --write-header. Units: centimetres.
// goalplanex is distinct from the end-net HalfLength.
namespace bbarena
{
inline constexpr double volumescale = 1.45;
inline constexpr double linearscale = 1.1318511959629507;
inline constexpr double goalplanex = 7244.7531351196549;
inline constexpr double halflength = 7754.0861733029824;
inline constexpr double halfwidth = 3622.3765675598274;
inline constexpr double eaveheight = 4760.8377745072012;
inline constexpr double apexheight = 7141.2566617608027;
inline constexpr double largehoopheight = 2103.1199999999999;
inline constexpr double smallhoopheight = 3048;
inline constexpr double hoopspacing = 1066.8;
inline constexpr double largehoopradius = 335.27999999999997;
inline constexpr double smallhoopradius = 198.12;
inline constexpr double freeshotdistance = 1341.1199999999999;
inline constexpr double restartdistance = 670.55999999999995;
}
