#pragma once
// Generated by Tools/arena_dimensions.py --write-header. Units: centimetres.
// GoalPlaneX is distinct from the end-net HalfLength.
namespace BBArena
{
inline constexpr double VolumeScale = 7.7333333333333334;
inline constexpr double LinearScale = 1.1318511959629507;
inline constexpr double LengthScale = 3.2013586238380256;
inline constexpr double WidthScale = 2.1342390825586834;
inline constexpr double LengthMultiplier = 2.8284271247461903;
inline constexpr double WidthMultiplier = 1.8856180831641267;
inline constexpr double BehindGoalBay = 509.3330381833278;
inline constexpr double GoalPlaneX = 21422.534622006217;
inline constexpr double HalfLength = 21931.867660189546;
inline constexpr double HalfWidth = 6830.4187598208109;
inline constexpr double EaveHeight = 4760.8377745072012;
inline constexpr double ApexHeight = 7141.2566617608027;
inline constexpr double LargeHoopHeight = 2103.1199999999999;
inline constexpr double SmallHoopHeight = 3048;
inline constexpr double HoopSpacing = 1066.8;
inline constexpr double LargeHoopRadius = 335.27999999999997;
inline constexpr double SmallHoopRadius = 198.12;
inline constexpr double FreeShotDistance = 1341.1199999999999;
inline constexpr double RestartDistance = 670.55999999999995;
}
