"""Shared arena dimensions for source art, tests, and the generated C++ contract.

Units are centimetres. Enclosure grows45% in volume; sporting distances and
physical player/ball/hoop sizes are deliberately independent.
"""
from pathlib import Path
import argparse

VOLUME_SCALE = 1.45
LINEAR_SCALE = VOLUME_SCALE ** (1.0 / 3.0)
BASELINE_GOAL_PLANE_X = 6400.8
BASELINE_HALF_LENGTH = 6850.8
BASELINE_HALF_WIDTH = 3200.4
BASELINE_EAVE_HEIGHT = 4206.24
BASELINE_APEX_HEIGHT = 6309.36
GOAL_PLANE_X = BASELINE_GOAL_PLANE_X * LINEAR_SCALE
HALF_LENGTH = BASELINE_HALF_LENGTH * LINEAR_SCALE
HALF_WIDTH = BASELINE_HALF_WIDTH * LINEAR_SCALE
EAVE_HEIGHT = BASELINE_EAVE_HEIGHT * LINEAR_SCALE
APEX_HEIGHT = BASELINE_APEX_HEIGHT * LINEAR_SCALE
LARGE_HOOP_HEIGHT = 2103.12
SMALL_HOOP_HEIGHT = 3048.0
HOOP_SPACING = 1066.8
LARGE_HOOP_RADIUS = 335.28
SMALL_HOOP_RADIUS = 198.12
FREE_SHOT_DISTANCE = 1341.12
RESTART_DISTANCE = 670.56
HEADER = Path(__file__).resolve().parents[1] / 'DevelopmentHarness/Source/BasketbroomRuntime/BBArenaDimensions.generated.h'


def dimensions(scale=LINEAR_SCALE):
    return {'half_x': BASELINE_HALF_LENGTH * scale, 'half_y': BASELINE_HALF_WIDTH * scale,
            'eave': BASELINE_EAVE_HEIGHT * scale, 'apex': BASELINE_APEX_HEIGHT * scale,
            'goal_x': BASELINE_GOAL_PLANE_X * scale}


def enclosed_volume_cm3(values=None):
    d = values if values is not None else dimensions()
    return 4 * d['half_x'] * d['half_y'] * (d['eave'] + (d['apex'] - d['eave']) / 3)


def header_text():
    entries = (
        ('VolumeScale', VOLUME_SCALE), ('LinearScale', LINEAR_SCALE),
        ('GoalPlaneX', GOAL_PLANE_X), ('HalfLength', HALF_LENGTH),
        ('HalfWidth', HALF_WIDTH), ('EaveHeight', EAVE_HEIGHT), ('ApexHeight', APEX_HEIGHT),
        ('LargeHoopHeight', LARGE_HOOP_HEIGHT), ('SmallHoopHeight', SMALL_HOOP_HEIGHT),
        ('HoopSpacing', HOOP_SPACING), ('LargeHoopRadius', LARGE_HOOP_RADIUS),
        ('SmallHoopRadius', SMALL_HOOP_RADIUS), ('FreeShotDistance', FREE_SHOT_DISTANCE),
        ('RestartDistance', RESTART_DISTANCE),
    )
    lines = ['#pragma once', '// Generated by Tools/arena_dimensions.py --write-header. Units: centimetres.',
             '// GoalPlaneX is distinct from the end-net HalfLength.', 'namespace BBArena', '{']
    lines += ['inline constexpr double %s = %s;' % (name, format(value, '.17g')) for name, value in entries]
    return '\n'.join(lines + ['}', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--write-header', action='store_true')
    parser.add_argument('--check-header', action='store_true')
    args = parser.parse_args()
    if args.write_header:
        HEADER.write_text(header_text(), encoding='utf-8', newline='\n')
    if args.check_header and HEADER.read_text(encoding='utf-8') != header_text():
        raise SystemExit('Generated arena dimensions header is stale')
    print('Enclosed volume ratio: %.12f' % (enclosed_volume_cm3() / enclosed_volume_cm3(dimensions(1.0))))
