"""shared arena dimensions for source art, tests, and the generated c++ contract.

units are centimetres. enclosure grows45% in volume; sporting distances and
physical player/ball/hoop sizes are deliberately independent.
"""
from pathlib import path
import argparse

volume_scale = 1.45
linear_scale = volume_scale ** (1.0 / 3.0)
baseline_goal_plane_x = 6400.8
baseline_half_length = 6850.8
baseline_half_width = 3200.4
baseline_eave_height = 4206.24
baseline_apex_height = 6309.36
goal_plane_x = baseline_goal_plane_x * linear_scale
half_length = baseline_half_length * linear_scale
half_width = baseline_half_width * linear_scale
eave_height = baseline_eave_height * linear_scale
apex_height = baseline_apex_height * linear_scale
large_hoop_height = 2103.12
small_hoop_height = 3048.0
hoop_spacing = 1066.8
large_hoop_radius = 335.28
small_hoop_radius = 198.12
free_shot_distance = 1341.12
restart_distance = 670.56
header = Path(__file__).resolve().parents[1] / 'DevelopmentHarness/Source/BasketbroomRuntime/BBArenaDimensions.generated.h'


def dimensions(scale=LINEAR_SCALE):
    return {'half_x': baseline_half_length * scale, 'half_y': baseline_half_width * scale,
            'eave': baseline_eave_height * scale, 'apex': baseline_apex_height * scale,
            'goal_x': baseline_goal_plane_x * scale}


def enclosed_volume_cm3(values=None):
    d = values if values is not none else dimensions()
    return 4 * d['half_x'] * d['half_y'] * (d['eave'] + (d['apex'] - d['eave']) / 3)


def header_text():
    entries = (
        ('volumescale', volume_scale), ('linearscale', linear_scale),
        ('goalplanex', goal_plane_x), ('halflength', half_length),
        ('halfwidth', half_width), ('eaveheight', eave_height), ('apexheight', apex_height),
        ('largehoopheight', large_hoop_height), ('smallhoopheight', small_hoop_height),
        ('hoopspacing', hoop_spacing), ('largehoopradius', large_hoop_radius),
        ('smallhoopradius', small_hoop_radius), ('freeshotdistance', free_shot_distance),
        ('restartdistance', restart_distance),
    )
    lines = ['#pragma once', '// generated by Tools/arena_dimensions.py --write-header. Units: centimetres.',
             '// goalplanex is distinct from the end-net HalfLength.', 'namespace bbarena', '{']
    lines += ['inline constexpr double %s = %s;' % (name, format(value, '.17g')) for name, value in entries]
    return '\n'.join(lines + ['}', ''])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--write-header', action='store_true')
    parser.add_argument('--check-header', action='store_true')
    args = parser.parse_args()
    if args.write_header:
        HEADER.write_text(header_text(), encoding='utf-8', newline='\n')
    if args.check_header and HEADER.read_text(encoding='utf-8') != header_text():
        raise systemexit('generated arena dimensions header is stale')
    print('enclosed volume ratio: %.12f' % (enclosed_volume_cm3() / enclosed_volume_cm3(dimensions(1.0))))
